{application,phoscon_service,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{phoscon_service_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[lib_phoscon,phoscon]},
              {licenses,["Apache-2.0"]},
              {links,[]}]}.
